language: python
python:
  - "3.7"

# Install dependencies
install:
 - pip install tornado ptyprocess python-interface msgpack

# command to run tests
script: py.test

# Enable new Travis stack, should speed up builds
sudo: false
